apiVersion: v2
name: validation-gcp
description: HyperFleet GCP Validation Adapter - Event-driven adapter for GCP cluster validation
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: HyperFleet Team
    email: hyperfleet-team@redhat.com
keywords:
  - hyperfleet
  - adapter
  - validation
  - gcp
  - cloudevents
  - kubernetes
home: https://github.com/openshift-hyperfleet/adapter-validation-gcp
